name: 'Shader Cache Version Check'
on:
  pull_request:
    branches:
      - master

jobs:
  check-shader-cache-version:
    name: Check Shader Cache Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Check Shader Cache Version
        shell: pwsh
        run: |
          $modified_files = git diff --name-only HEAD^1 HEAD
          Write-Host $modified_files
          $shaders_modified = false
          $shader_version_modified = false;
          foreach ($file in $modified_files)
          {
            if (-not $shaders_modified)
            {
              Write-Host "Shader: ""$file"" was modified."
              $shaders_modified = $file.StartsWith("bin/resources/shaders/")
            }
            if (-not $shader_version_modified)
            {
              $shader_version_modified = $file -eq "pcsx2/ShaderCacheVersion.h"
            }
          }
          if ($shader_version_modified)
          {
              $modified_cache = git diff HEAD^1 HEAD -- "pcsx2/ShaderCacheVersion.h"
              $old_ver = if ($modified_cache -match '^\-static constexpr u32 SHADER_CACHE_VERSION = (\d+);') { $Matches.1 } else { -1 }
              $new_ver = if ($modified_cache -match '^\+static constexpr u32 SHADER_CACHE_VERSION = (\d+);') { $Matches.1 } else { -1 }
              if (($old_ver -eq -1) -or ($new_ver -eq -1) -or ($old_ver -eq $new_ver))
              {
                Write-Host "ShaderCacheVersion.h was modified, but version was unchanged."
                $shader_version_modified = false
              }
              else
              {
                Write-Host "ShaderCacheVersion.h was modified"
                Write-Host "Old shader cache version: $old_ver."
                Write-Host "New shader cache version: $new_ver."
              }
          }
          
          Write-Host $shaders_modified
          Write-Host $shader_version_modified
          
          -not ($shader_version_modified -xor $shaders_modified)
